# Site settings
title: We are a team of skilled developers with  unlimited possibilities
twitter_username: evolcoderss
name: EvolCoders

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://automateddeveloper.blogspot.com/
 - title: GitHub
   url: https://github.com/evolcoders

#Any buzzword skills you want to include
skills:
 - C#
 - Asp.Net
 - Net Core
 - Entity Framework
 - TypeScript
 - Angular
 - Sql
 - MSSql/Mysql
 - REST
 - Tech Architecture

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: http://automateddeveloper.blogspot.com/feeds/posts/default?alt=rss

#Work experience is required
team_members:
 - title: Ivan Chupikov
   position: spokesmen
   description: motivator for coders
 - title: Nik Osipov
   position: chief developer
   description: create a magic
 - title: Anrew Titov
   position: chief developer
   description: beer rickshaw


#List of interesting Github repo/projects to include - optional
github:
 - evolcoders/learning-neural-networks


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
